---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: tf2report

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tf2report/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin
    ldflags:
      - -s -w -X 'main.appVersion={{.Version}}' -X 'main.buildCommit={{.Commit}}' -X 'main.buildTime={{.CommitDate}}'

archives:
  - formats: "tar.gz"
    name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "386" -}}
        i386
      {{- else -}}
        {{ .Arch }}
      {{- end -}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
