---
name: GitHub Pages
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'docs/github-pages/pnpm-lock.yaml'

      - name: Build static files
        id: build
        run: |
          cd docs/github-pages/
          pnpm install
          pnpm build
        env:
          TF2REPORT_VERSION: ${{ github.ref_name }}

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/github-pages/build/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: "https://tf2report.germainlefebvre.fr"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
